name: example
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.9.0
  logger: ^2.6.1
  shared_preferences: ^2.5.3
  flutter_mana: any
  flutter_mana_kits: any

dependency_overrides:
  flutter_mana:
    path: ../
  flutter_mana_kits:
    path: ../flutter_mana_kits/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/test.jpeg

