name: flutter_mana
description: "Mana is an in-app debug kits platform for Flutter. Flutter应用内调试工具平台"
version: 1.0.0-beta.3
homepage: https://github.com/lhlyu/flutter_mana

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  device_info_plus: ^11.5.0
  dio: ^5.8.0+1
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

