name: flutter_mana_kits
description: "Flutter Mana Kits"
version: 1.0.4
homepage: https://github.com/lhlyu/flutter_mana/tree/master/flutter_mana_kits

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_mana: ^1.0.2
  dio: ^5.9.0
  logger: ^2.6.1
  shared_preferences: ^2.5.3
  device_info_plus: ^11.5.0
  syntax_highlight: ^0.4.0
  package_info_plus: ^8.3.1
  vm_service: ^15.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0